title: Your Site Title
description: A brief description of your site
author:
  name: Your Name
  email: your-email@example.com

# Build settings
markdown: kramdown
remote_theme: alshedivat/al-folio

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
github_username: your-github-username
twitter_username: your-twitter-username

# Google Analytics
google_analytics: UA-XXXXXXXXX-X
