title: David A. McElfresh
description: I am a synthetic biologist completing my BS/MS in Molecular Biophysics & Biochemistry at Yale University, where I have focused on synthetic biology approaches to engineer the genomes of non-model microbes. My interests include designing and leveraging genome editing tools to address challenges in carbon capture biotechnology. This fall, I will join Princeton University as a graduate student in Molecular Biology to further explore innovative solutions at the intersection of synthetic biology and the environment.
author:
  name: David A. McElfresh
  email: david.mcelfresh@yale.edu
  curriculum:
    - url: https://drive.google.com/file/d/1GY8hNoCp9iV27ZP-7H9Wl_DtQuLBRYzW/view?usp=sharing
# Build settings
markdown: kramdown
remote_theme: gaalcaras/academic

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Inclusions
include:
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmcelfresh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
email: david.mcelfresh@yale.edu
linkedin_username: david-mcelfresh
bluesky_username: dmcelfresh
github_username: dmcelfresh
orcid_id: 0009-0000-6925-4656

# Google Analytics
google_analytics: UA-XXXXXXXXX-X
