title: David A. McElfresh
description: Hi! My name is David A. McElfresh, and I am a current BS/MS researcher at Yale University majoring in Molecular Biophysics & Biochemistry. I am conducting my Master's thesis in the Farren Isaacs lab developing novel technologies for the diversification of nonmodel genomes.
author:
  name: David A. McElfresh
  email: david.mcelfresh@yale.edu

# Build settings
markdown: kramdown
remote_theme: gaalcaras/academic

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Inclusions
include:
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
        
# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmcelfresh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
email: david.mcelfresh@yale.edu
linkedin_username: david-mcelfresh
bluesky_username: dmcelfresh
github_username: dmcelfresh
orcid_id: 0009-0000-6925-4656

# Google Analytics
google_analytics: UA-XXXXXXXXX-X
