title: David A. McElfresh
description: David A. McElfresh is a synthetic biologist and incoming Molecular Biology PhD student at Princeton University.
author:
  name: David A. McElfresh
  email: david.mcelfresh@yale.edu
  curriculum:
    - name: Curriculum Vitae
    - url: https://drive.google.com/file/d/1GY8hNoCp9iV27ZP-7H9Wl_DtQuLBRYzW/view?usp=sharing
# Build settings
markdown: kramdown
remote_theme: gaalcaras/academic

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Inclusions
include:
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmcelfresh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
email: david.mcelfresh@yale.edu
linkedin_username: david-mcelfresh
bluesky_username: dmcelfresh
github_username: dmcelfresh
orcid_id: 0009-0000-6925-4656
twitter: davidamcelfresh

# Google Analytics
google_analytics: UA-XXXXXXXXX-X
